name: khidmat
description: "A two-in-one mobile app connecting needy applicants with generous donors"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  google_fonts: ^6.2.1
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.5.1
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Navigation & Routing
  go_router: ^14.6.2
  
  # Animations
  lottie: ^3.3.0
  flutter_staggered_animations: ^1.1.1
  
  # Phone Auth & OTP
  firebase_auth: ^5.3.3
  firebase_core: ^3.9.0
  pinput: ^5.0.0
  
  # Image & File Handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Storage & Path
  path_provider: ^2.1.4
  
  # Responsive Design
  flutter_screenutil: ^5.9.3
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  country_code_picker: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  riverpod_generator: ^2.5.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
